services: 
  container_db:
    container_name: sql_server_gauss
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrongP@ssw0rd!"  # Definir uma senha forte com no mínimo 8 caracteres
      ACCEPT_EULA: "Y"
    volumes:
      - type: volume
        source: db_sql_srv
        target: /var/opt/mssql
    networks:
      - gauss-network
    privileged: true

  php:
    container_name: web_gaussFleet
    image: ryckrodriguez/gaussfleet
    ports:
      - "8888:80"
    volumes:
      - ./:/var/www/html
    networks: 
      - gauss-network
    depends_on:
      - container_db

networks: 
  gauss-network:
    driver: bridge

volumes:
  db_sql_srv: